"""fixed name

Revision ID: 3ef26dcb77f7
Revises: 25b0d1692bee
Create Date: 2024-08-30 21:05:17.704958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef26dcb77f7'
down_revision: Union[str, None] = '25b0d1692bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('rooms', 'descrpition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('descrpition', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
